title: Jake Skelton's Portfolio

description: A place for me to share electronics, coding, physics, and maths
 projects.

url: "https://jakeskelton.co.uk"

# Specify the name of a file to show as a masthead graphic at the top of each page, instead of a title, here:
masthead: /favicon.png

#theme: minimal
theme: minima
# remote_theme: pages-themes/minimal@v0.2.0


plugins:
- jekyll-remote-theme
- jekyll-seo-tag


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true