title: Jake Skelton's Portfolio
description: A place for me to share electronics, coding, physics, and maths
 projects.
#baseurl: ""
url: "https://jakeskelton.co.uk"
#theme: minimal
theme: minima
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag